[telegram]
bot_token = ''
administrator = 0 # Telegram user id of the bot administrator

[google]
api_key = ''           # Google API Token to access Google Sheets API for gift list
spreadsheet_id = ''
sheet_id = ''
data_range = 'A1:AB30' # select the area where to search for whishes in sheet

[flantier]
extended_mode = false # enable gifts management features
