[telegram]
TOKEN = ''        # Telegram bot token
administrator = 0 # Telegram user id of the bot administrator

[google]
API_key = ''           # Google API Token to access Google Sheets API for gift list
spreadsheet_id = ''
sheet_id = ''
data_range = 'A1:AB30' # where to search for data in the sheet

[flantier]
extended_mode = false # enable gifts management features
